#!/bin/sh
# . "$(dirname "$0")/_/husky.sh"

# npm run lint-check && git add -u
echo -e "\n >>> CHECKING linter \033[0;32m(read-only) \033[0m"
cd contracts/ && make fmt
npm run lint-check
LINT_PASS=$?

if [ $LINT_PASS -ne 0 ];
then
  echo -e "\033[0;31m >>> Lint check failed: \033[0m"
  echo "1. Stage your changes; git add"
  echo "2. Run lint fixer ; npm run lint-fix'"
  exit 2
fi;
echo -e "\n \033[0;32m LINT CHECK PASSED,  \033[0m"
